<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <RootNamespace>Kargoyeri.Studio.Core</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591;1573</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Kargoyeri.Application\Kargoyeri.Application.csproj" />
    <ProjectReference Include="..\Kargoyeri.Contracts\Kargoyeri.Contracts.csproj" />
    <ProjectReference Include="..\Kargoyeri.Domain\Kargoyeri.Domain.csproj" />
    <ProjectReference Include="..\Kargoyeri.Infrastructure\Kargoyeri.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
  </ItemGroup>

</Project>
