<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Kargoyeri.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Kargoyeri.Application\Kargoyeri.Application.csproj" />
    <ProjectReference Include="..\Kargoyeri.Contracts\Kargoyeri.Contracts.csproj" />
    <ProjectReference Include="..\Kargoyeri.Domain\Kargoyeri.Domain.csproj" />
  </ItemGroup>

</Project>
